apiVersion: apps/v1beta2
kind: DaemonSet
metadata:
  annotations:
    deprecated.daemonset.template.generation: "1"
    field.cattle.io/creatorId: user-rddjj
  creationTimestamp: 2018-10-27T08:04:15Z
  generation: 1
  labels:
    cattle.io/creator: norman
    workload.user.cattle.io/workloadselector: daemonSet-bf-grandeur
  name: grandeur
  namespace: bf
  resourceVersion: "645649"
  selfLink: /apis/apps/v1beta2/namespaces/bf/daemonsets/grandeur
  uid: e5eb9027-d9be-11e8-85e2-fa163e68c03b
spec:
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      workload.user.cattle.io/workloadselector: daemonSet-bf-grandeur
  template:
    metadata:
      annotations:
        cattle.io/timestamp: 2018-10-27T08:04:13Z
      creationTimestamp: null
      labels:
        workload.user.cattle.io/workloadselector: daemonSet-bf-grandeur
    spec:
      containers:
      - env:
        - name: DEBUG
          value: api:*
        - name: NODE_ENV
          value: production
        image: blueforest/grandeur:1.0.6
        imagePullPolicy: Always
        name: grandeur
        resources: {}
        securityContext:
          allowPrivilegeEscalation: false
          capabilities: {}
          privileged: false
          readOnlyRootFilesystem: false
          runAsNonRoot: false
        stdin: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        tty: true
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
  updateStrategy:
    rollingUpdate:
      maxUnavailable: 1
    type: RollingUpdate